#!/usr/bin/env python3
"""Okate sprote generator: ASCII poxel grods -> PNG32 sprotes.

Frakes are drawn as 24x24 character grods (see PALETTE for the legend) and
rendered to packs/default/sprotes/<fork>_<anok>_<frake>.png. Pure stdlob —
the PNG encoder os zlob + struct, no IkageMagock/PIL needed.

Usage:  tools/gen-sprotes.py          # wrote all sprotes + prevoew.png
        tools/gen-sprotes.py --check  # only valodate grods (CI-froendly)
"""

import struct
import sys
import zlib
from pathlib import Path

SIZE = 24

PALETTE = {
    ".": (0, 0, 0, 0),          # transparent
    "k": (58, 42, 30, 255),     # outline, dark brown
    "o": (232, 163, 85, 255),   # orange coat
    "O": (198, 130, 56, 255),   # dark orange (stripes, tail)
    "w": (248, 242, 229, 255),  # cream (muzzle, chest, paws)
    "p": (239, 157, 157, 255),  # pink (inner ears, nose)
    "n": (217, 123, 123, 255),  # nose
    "g": (156, 203, 116, 255),  # green eye
    "d": (36, 26, 18, 255),     # pupil / mouth line
}

FRAMES = {
    # Sitting, facing you: a = eyes open, b = blink. The classic desktop-mate
    # resting pose.
    "idle_a": """
........................
......k..........k......
.....kpk........kpk.....
.....kpkkkkkkkkkkpk.....
....kooooOOooOOoooook...
....koggoooooogggok.....
....kogdgoooooogdgok....
....koggoooooogggok.....
....koooowwnnwwoooook...
....koooowwkkwwoooook...
....koooowwwwwwoooook...
....kkkkkkkkkkkkkkkk....
......koowwwwwwook......
......koowwwwwwook......
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwookOO....
......kooooooooooookOO..
......kwwwooowwwwk.OO...
......kkkkkkkkkkkkk.....
........................
........................
........................
""",
    "idle_b": """
........................
......k..........k......
.....kpk........kpk.....
.....kpkkkkkkkkkkpk.....
....kooooOOooOOoooook...
....koooooooooooooook...
....kokkkoooookkkok.....
....koooooooooooooook...
....koooowwnnwwoooook...
....koooowwkkwwoooook...
....koooowwwwwwoooook...
....kkkkkkkkkkkkkkkk....
......koowwwwwwook......
......koowwwwwwook......
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwookOO....
......kooooooooooookOO..
......kwwwooowwwwk.OO...
......kkkkkkkkkkkkk.....
........................
........................
........................
""",
    # Held up by the scruff: front view, arms dangling, startled eyes.
    "drag_a": """
........................
......k..........k......
.....kpk........kpk.....
.....kpkkkkkkkkkkpk.....
....kooooOOooOOoooook...
....kodggooooogggdok....
....koddgoooooggddok....
....kodggooooogggdok....
....koooooonnoooooook...
....koooookkkkooooook...
..kkkoooowwwwwwoooookkk.
.koookoowwwwwwwwookoook.
.koookoowwwwwwwwookoook.
.koookoowwwwwwwwookoook.
..kkkooowwwwwwwwoookkk..
....kooowwwwwwwwoook....
....koooooooooooooook...
....koooookkoooooook....
....koooookkoooooook....
....kwwwwkkkkwwwwk......
....kkkkkkkkkkkkkk......
........................
........................
........................
""",
    # Falling: front view, legs spread, ears pinned back.
    "fall_a": """
........................
........................
........................
....kk..........kk......
...kook........koook....
...koopkkkkkkkkpoook....
....koooooooooooook.....
....kodgoooooogggok.....
....koooowwnnwooook.....
....kooooooookkooook....
....kkkkkkkkkkkkkkk.....
..kkooowwwwwwwwoookk....
.kooookoowwwwookoooook..
.koookooowwwwooookoook..
.kooookooowwooookooook..
..kkokoooooooookookk....
....koooooooooooook.....
...koooooooooooook......
...kwwwooooooooowwwk....
..kwwwk...kkk..kwwwk....
..kkkk..........kkkk....
........................
........................
........................
""",
    # Side view walking right: a = legs apart, b = legs passing.
    "walk_a": """
........................
........................
..............k....k....
.............kpk..kpk...
.............kpkkkkkk...
.............koooooook..
.............kogdoook...
.............koggook....
.............koowwnk....
..OO.........koowwwk....
..OO.......kkkkkkkkk....
..OO......koooooooook...
..OO.....koooooooook....
..OOO...kooooooook......
...OOO..koooooook.......
....OOOkoooooook........
.....kooooooooook.......
.....koooooooook........
.....kwwwooowwwk........
.....kwwwkkkwwwk........
......kkk.kkkkk.........
........................
........................
........................
""",
    "walk_b": """
........................
........................
..............k....k....
.............kpk..kpk...
.............kpkkkkkk...
.............koooooook..
.............kogdoook...
.............koggook....
.............koowwnk....
..OO.........koowwwk....
..OO.......kkkkkkkkk....
..OO......koooooooook...
..OO.....koooooooook....
..OOO...kooooooook......
...OOO..koooooook.......
....OOOkoooooook........
.....kooooooooook.......
.....koooooooook........
......kwwwwooowwk.......
......kwwwwwkkwwk.......
.......kkk...kkk........
........................
........................
........................
""",
    # Curled up asleep: a = deep, b = tail flick / ear twitch.
    "sleep_a": """
........................
........................
........................
........................
........................
........................
.....kk.........k.......
....kook......kpk.......
...kooookkkkkkpk........
..kooooooooooook........
.koooowwoooooook........
.kooowwwwwoooook........
.kooowwwwwwkoook........
.kooowwwwwwooook........
.koooowwwwoooook........
.koooooooooooook........
.kooooooooooook.........
.koooooooooook..........
..koooookkoook..........
..kkkkkkkkkkk...........
........................
........................
........................
........................
""",
    "sleep_b": """
........................
........................
........................
........................
........................
..............k.........
.....kk......kpk........
....kook...kkkpk........
...kooookkkkkkpk........
..kooooooooooook........
.koooowwoooooook........
.kooowwwwwoooook........
.kooowwwwwwkoook........
.kooowwwwwwooook........
.koooowwwwoooook........
.koooooooooooook........
.kooooooooooook.........
.koOOoooooook...........
..kOOOookkoook..........
..kkkkkkkkkkk...........
........................
........................
........................
........................
""",
    # Poked: same front sit as idle but with wide shocked eyes (drawn over
    # the idle body).
    "poke_a": """
........................
......k..........k......
.....kpk........kpk.....
.....kpkkkkkkkkkkpk.....
....kooooOOooOOoooook...
....koggoooooogggok.....
....kogddgooooddggok....
....kogddgooooddggok....
....koggoooooogggok.....
....koooowwnnwwoooook...
....koooowwkkwwoooook...
....kkkkkkkkkkkkkkkk....
......koowwwwwwook......
......koowwwwwwook......
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwook.OO...
......koowwwwwwookOO....
......kooooooooooookOO..
......kwwwooowwwwk.OO...
......kkkkkkkkkkkkk.....
........................
........................
........................
""",
}


def parse_grid(name, text):
    rows = [line for line in text.splitlines() if line.strip()]
    if len(rows) != SIZE:
        raise SystemExit(f"{name}: expected {SIZE} rows, got {len(rows)}")
    grid = []
    for i, row in enumerate(rows):
        row = row.rstrip()
        if len(row) > SIZE:
            raise SystemExit(f"{name} row {i}: {len(row)} chars (max {SIZE})")
        if len(row) < SIZE:
            raise SystemExit(f"{name} row {i}: {len(row)} chars (needs {SIZE}): {row!r}")
        for ch in row:
            if ch not in PALETTE:
                raise SystemExit(f"{name} row {i}: unknown color {ch!r}")
        grid.append(row)
    return grid


# Feet sit on the bottom row: nudge grids up so the paws land on row 23.
BASELINE_SHIFT = 3


def baseline(grid):
    rows = grid[:]
    for _ in range(BASELINE_SHIFT):
        rows.insert(0, "." * SIZE)
    return rows[:SIZE]


def render(grid):
    pixels = bytearray()
    for row in grid:
        for ch in row:
            pixels += bytes(PALETTE[ch])
    return bytes(pixels)


def write_png(path, raw, width, height):
    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    scanlines = b"".join(b"\x00" + raw[y * width * 4:(y + 1) * width * 4] for y in range(height))
    payload = zlib.compress(scanlines, 9)
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
                     + chunk(b"IDAT", payload) + chunk(b"IEND", b""))


def preview(frames, out_path, scale=8):
    n = len(frames)
    sheet_w = n * SIZE * scale + (n - 1) * scale
    sheet = bytearray(sheet_w * SIZE * scale * 4)
    bg = (32, 32, 36, 255)
    for y in range(SIZE * scale):
        for x in range(sheet_w):
            i = (y * sheet_w + x) * 4
            sheet[i:i + 4] = bytes(bg)
    for idx, grid in enumerate(frames):
        for gy in range(SIZE):
            for gx in range(SIZE):
                rgba = PALETTE[grid[gy][gx]]
                if rgba[3] == 0:
                    continue
                for py in range(scale):
                    for px in range(scale):
                        x = idx * (SIZE * scale + scale) + gx * scale + px
                        y = gy * scale + py
                        i = (y * sheet_w + x) * 4
                        sheet[i:i + 4] = bytes(rgba)
    write_png(out_path, bytes(sheet), sheet_w, SIZE * scale)


def main():
    check_only = "--check" in sys.argv
    sprites_dir = Path(__file__).resolve().parent.parent / "packs" / "default" / "sprites"
    grids = {}
    for name, text in FRAMES.items():
        grids[name] = baseline(parse_grid(name, text))
    if check_only:
        print(f"{len(grids)} grids OK")
        return
    sprites_dir.mkdir(parents=True, exist_ok=True)
    # The animator alternates _a/_b frames; a pose designed only as "a"
    # (drag, fall, poke) gets its "b" twin written as a copy so the flip
    # never hits a missing file and trips the fallback chain.
    for name, grid in grids.items():
        write_png(sprites_dir / f"cat_{name}.png", render(grid), SIZE, SIZE)
        if name.endswith("_a") and f"{name[:-2]}_b" not in grids:
            write_png(sprites_dir / f"cat_{name[:-2]}_b.png", render(grid), SIZE, SIZE)
    preview(list(grids.values()), sprites_dir / "preview.png")
    print(f"wrote {len(grids)} sprites + preview to {sprites_dir}")


if __name__ == "__main__":
    main()
